apiVersion: 1
groups:
    - orgId: 1
      name: Sanoptes
      folder: Sanoptes
      interval: 1m
      rules:
        - uid: aenphtlgo1ssgb
          title: Новый открытый порт
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: "sum by (host, port) (\r\n  nmap_port_scan{state=\"open\"}\r\n) unless\r\nsum by (host, port) (\r\n  nmap_port_scan{state=\"open\"} offset 15m\r\n)"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: |-
                {{ $labels.host }} has new open port {{ $labels.port }} ({{ $labels.service }})
                IP: {{ $labels.ip }}
                Version: {{ $labels.version }}
          isPaused: false
          notification_settings:
            receiver: Telegram
