{
 "title": "Sanoptes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "3m",
 "panels": [
  { "title": "Sanoptes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Активные хосты",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (host)(nmap_port_scan))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Открытые порты",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(port) (nmap_port_scan{state=\"open\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Динамика фильтруемых портов",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(host) (nmap_port_scan{state=\"filtered\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Динамика открытых портов",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(host) (nmap_port_scan{state=\"open\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Открытые порты",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by(port) (nmap_port_scan{state=\"open\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Хосты",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "sum by (host,ip,state) (nmap_port_scan)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Обнаруженные сервисы",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 11 },
   "targets": [
    {
     "expr": "sum by(version) (nmap_port_scan{version!=\"unknown\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}